### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by robertoaloi** [textmate/erlang.tmbundle#20]
Hi @infininight and @sorbits , we are maintaining the Erlang Language Server project (https://github.com/erlang-ls/erlang_ls) and the respective VSCode extension (https://github.com/erlang-ls/vscode/), including this repo as a dependency for the syntax highlighting part.

Some contributors recently opened some issues/PRs towards this repo, but it looks like the Erlang part is not actively maintained any longer. We may have people interested in contributing. Any input on this?

**Comment by sorbits** [comment]
> Any input on this?

We would appreciate contributors and/or new maintainers, as there are too many bundles for me and @infininight to manage.

But all these bundles were created for, and are still used with, TextMate, so they must remain compatible with TextMate.
